### PR TITLE
optionally prune or archive old vers (#29)

### PR DESCRIPTION
**Pull request by leeper**
There are three main changes here, as we discussed in #29:

1. A new function `archivePackages` that will create and move older package versions into an Archive folder.
2. A new argument `action` for `insertPackage`, with a default value "none" that leaves current behavior unmodified. The two new options are "prune" (calling `pruneRepo`) or "archive" (calling `archivePackages`).
3. A new argument to `pruneRepo` that allows package-specific pruning (which is what happens when you do `insertPackage(action = "prune")`). Because `archivePackages` calls `pruneRepo` to get a list of old package versions, this also means that `archivePackages` can do package-specific archiving, too.

I also added examples demonstrating `archivePackages` and the new `action` argument, and ran `document()` on everything.

I bumped the patch version and date accordingly.

Note: Following from the current status of the overall package, all of this really only works on source tarballs.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Just glancing at it now -- looks good.  (I usually call interim versions 0.0.4.1, say, but that is minor.)  

Will test. Question then is whether to release now, and wait on the "still pending" work for binaries...

**Comment by leeper** [comment]
Would you like me to change the version and resubmit?

**Comment by eddelbuettel** [comment]
Sure, maybe as 0.0.4.1?  Either way is fine.  I can merge as is as well.

Currently being busy with another package but drat is next :)

**Comment by eddelbuettel** [comment]
Thank you.  True master with a squashed commit.  Wow.  I am usually too lazy for this :)

**Comment by eddelbuettel** [comment]
And the binary is now in the [ghrr](http://ghrr.github.io/drat/) drat  -- mostly because my work machines etc already look at that, and it keeps the drat repo a little smaller which matters as people still fork it...

**Comment by leeper** [comment]
Sounds good!

**Comment by eddelbuettel** [comment]
Sorry for sitting on this -- other packages got in the way.  Full(er) steam ahead for a 0.0.5 release now.

**Comment by leeper** [comment]
Great!

**Comment by eddelbuettel** [comment]
And thanks for closing my open tickets for me :)   Was once again busy with "yet another package" :)

**Pull request merged**
