### PR TITLE
fix for support dots, solves #39

### PR DESCRIPTION
**Pull request by jangorecki**
tested on `data.table_1.9.6.zip` file.
I could add tests for that fix but I would need to keep `drat_1.0.0.zip` locally in `inst`.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Confirmed. 

I am not sure what you are trying to say with 

>  I could add tests for that fix but I would need to keep drat_1.0.0.zip locally in inst.

**Comment by jangorecki** [comment]
wait

**Comment by eddelbuettel** [comment]
Worked here:

```
R> gsub("^([a-zA-Z0-9._]*)_.*", "\\1", basename("data.table_1.9.6"))
[1] "data.table"
R> gsub("^([a-zA-Z0-9._]*)_.*", "\\1", basename("data._table_1.9.6"))
[1] "data._table"
R> gsub("^([a-zA-Z0-9._]*)_.*", "\\1", basename("data_table_1.9.6"))
[1] "data_table"
R> 
```

I will not merge a patch for just dots.

**Comment by jangorecki** [comment]
@eddelbuettel if underscore in the package name is not considered to be valid then why you would like to handle them?

**Comment by eddelbuettel** [comment]
Oh, I would accept that as a counter argument :)   Does _Writing R Extension_ prohibit it?

**Comment by eddelbuettel** [comment]
Ok, found it:

>    The mandatory 'Package' field gives the name of the package.  This
should contain only (ASCII) letters, numbers and dot, have at least two
characters and start with a letter and not end in a dot.  If it needs
explaining, this should be done in the 'Description' field (and not the
'Title' field).

Convinced now :)

**Pull request merged**
