### PR TITLE
Problems with commit due to reldir and system call in Windows

### PR DESCRIPTION
**Pull request by roliveros-ramos**
I found I was not able to commit in Windows due to the quote in the commit message (error in the call):

> Warning message:
> running command 
> 'git add kali_0.0.6.tar.gz PACKAGES PACKAGES.gz; 
> git commit -m"Adding kali_0.0.6.tar.gz to drat"; 
> git push' had status 129 
> 
> error: unknown switch `m'

This is fixed using shQuote(msg) and system2 (it shouldn't break anything on linux).

Also, "reldir" was duplicated when adding files using git2r, so files where not added to the commit:

> using git2r
> Warning message:
> In git2r::commit(repo, msg) :
> Error in 'git2r_commit': Nothing added to commit

Then I noticed it was the same for 'hascmd' but only for PACKAGES.rds. The duplication of relative paths has been removed.
It works for me now.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sorry.  That PR changes WAY too many things all once, and will affect code that is moderately widely used and tested, across several OSs.

As it stands I will not merge it.

We could close this and work more minimally one issue at a time.  Not four at once.

**Comment by roliveros-ramos** [comment]
I understand. 
I think the relative paths duplicated to "reldir" are the bigger issue. Could you reproduce that error?

**Comment by eddelbuettel** [comment]
I have to admit I am not sure what you are referring to.  Can you point to a line here:  
https://github.com/eddelbuettel/drat/blob/70a6a179c6d9a2b2653c4af183c76cfda9fbdd5d/R/insertPackage.R#L105-L139
And explain what you think is wrong, and why, and what you suggest changing?  I myself have commited countless files that way...

**Comment by eddelbuettel** [comment]
Also, re your quoting issue;  Most folks recommend git-bash for Windows.  You weren't trying cmd.exe were you?

**Comment by eddelbuettel** [comment]
Closing this now for lack of follow-up to issues raised.  

Maybe best to first open issue tickets to discuss what to change.

**Pull request closed without merging**
