### PR TITLE
allow absolute filenames

### LINKED ISSUE #7: insertPackage should work with absolute filenames?
The following code:
```
drat::insertPackage('/home/spav/trunk/code/r/staging/foo.plot_0.1.tar.gz',
 repodir='/mnt/NAS/installers/r/drat/')
```
fails with an error like:
```
In file.copy(file.path(curwd, file), srcdir, overwrite = TRUE) :
  problem copying /home/spav/myworking/directory/basically/pwd//home/spav/trunk/code/r/staging/foo.plot_0.1.tar.gz  to /mnt/NAS/installers/r/drat//src/contrib/foo.plot_0.1.tar.gz: No such file or directory
```
I am using drat 0.2.0 with git2r, from the directory /home/spav/myworking/directory/basically/pwd

### PR DESCRIPTION
**Pull request by shabbychef**
Attempts to copy to curwd/file, then to file. Fixes #7.

### CODE REVIEW

**Comment by shabbychef** [comment]
once more with feeling.

**Comment by eddelbuettel** [comment]
Closing this as we addressed it something differently; thanks though for the reminder about `basename()`.

**Comment by shabbychef** [comment]
not a problem, glad to have helped.

**Comment by eddelbuettel** [comment]
:+1: 

I put a new drat binary in drat's own repo, but if you follow the git checkout (of the sources) you may already have it.

**Pull request closed without merging**
