### PR TITLE
packageHtml to render basic html

### PR DESCRIPTION
**Pull request by jangorecki**
Creates basic homepage for package oriented drat repository.
Renders package manual to html, links from homepage.
Package install string in homepage, automatically adds *additional repositories* from DESCRIPTION file. Optionally includes CRAN repo url.
I'm going to use it as a complement to drat repo itself, may be useful for others and requires no dependency, but makes an installation of a package into new temporary library, removed on exit.
Manual for new function available in [packageHtml.html](https://jangorecki.github.io/drat/html/packageHtml.html).
Feedback welcome, ready to merge.

Possibly future extension to include doc, so vignettes results.

### CODE REVIEW

**Comment by jangorecki** [comment]
The result from the *examples* can be viewed here: https://jangorecki.github.io/drat/
Will add another one more complex soon.

**Comment by eddelbuettel** [comment]
I generally welcome issue tickets _before_ pull requests to discuss what does, or does not, fit within the scope of the package.

I am currently unsure about the need for default html documentation, and on top of that the continuous integration appears to have bombed (maybe simply because of missing new Depends: ...).  So currently not exactly in favour...

**Comment by jangorecki** [comment]
@eddelbuettel that's fine for me, I have no problem to stay with my fork. Feel free to close.
Another example, comparing to previous one, this uses *additional repository* and *URL* from DESCRIPTION file, and a CI git branch and commit from env vars.
https://jangorecki.gitlab.io/logR/ - produced by `drat::packageHtml(repodir = "logR", repo.url = "https://jangorecki.github.io/logR", manual = TRUE)`.

**Comment by eddelbuettel** [comment]
Ok, closing this for now.  

It is a little out of scope as currently defined, plus it appears to have broken the build.

**Comment by jangorecki** [comment]
Build failed with `The command "./travis-tool.sh run_tests" exited with 1.`, particularly
```
* creating vignettes ... ERROR

Warning in engine$weave(file, quiet = quiet, encoding = enc) :

  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.

Error: processing vignette 'CombiningDratAndTravis.Rmd' failed with diagnostics:

It seems you should call rmarkdown::render() instead of knitr::knit2html() because CombiningDratAndTravis.Rmd appears to be an R Markdown v2 document.

Execution halted
```
doesn't seem to be related to that PR.

**Comment by eddelbuettel** [comment]
It still checks fine here with R 3.2.3 and everything else current:

```bash
edd@max:~/git$ R CMD check drat_0.1.0.tar.gz       
* using log directory ‘/home/edd/git/drat.Rcheck’
* using log directory ‘/home/edd/git/drat.Rcheck’
* using R version 3.2.3 (2015-12-10)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘drat/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘drat’ version ‘0.1.0’
* checking package namespace information ... OK
[...]
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘simpleTests.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
   ‘CombiningDratAndTravis.Rmd’ using ‘UTF-8’ ... OK
   ‘DratFAQ.Rmd’ using ‘UTF-8’ ... OK
   ‘DratForPackageAuthors.Rmd’ using ‘UTF-8’ ... OK
   ‘DratForPackageUsers.Rmd’ using ‘UTF-8’ ... OK
   ‘WhyDrat.Rmd’ using ‘UTF-8’ ... OK
 OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: OK

edd@max:~/git$ 
```

**Comment by eddelbuettel** [comment]
So this appears to have failed because my `.travis.yml` needed an update, rather than because of your code.

That said, I am not convinced me need this in drat so not suggesting to reopen it.

**Pull request closed without merging**
