### PR TITLE
Support windows and macosx binary packages

### PR DESCRIPTION
**Pull request by JanSchulz**
This commit adds support for windows and macosx binary packages. 
Package type is automatically inferred from the filename.
    
It also creates the package structure
(`./{src|bin/windows|bin/macosx}/contrib/{rversion/|}`) if these
dirs do not exist.
    
This is lightly tested with 
```
R CMD INSTALL --build drat
# in R
library(drat)
options(dratRepo="C:\\temp\\drat3")
drat:::insert("C:\\Rtools\\rzmq_0.7.7.tar.gz")
drat:::insert("C:\\Rtools\\rzmq_0.7.7.zip")
install.packages("rzmq", repos="file:c:/temp/drat3/")
```

which then actually installs the rzmq binary file. 

It also works on my github page, which is build after the workflow in #11:
```
> drat::addRepo("janschulz")
> install.packages("rzmq")
Installing package into ‘C:/portabel/Rlibs’
(as ‘lib’ is unspecified)
trying URL 'http://janschulz.github.io/drat/bin/windows/contrib/3.1/rzmq_0.7.7.zip'
Content type 'application/zip' length 681860 bytes (665 KB)
opened URL
downloaded 665 KB

package ‘rzmq’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘rzmq’

The downloaded binary packages are in
	C:\Users\jschulz\AppData\Local\Temp\RtmpcdQEMD\downloaded_packages
```

I have no Macosx so I can't test that aspect :-(

Closes: #4

### CODE REVIEW

**Comment by eddelbuettel** [comment]
This is still an open issue but the code moved away from this.  We need to revisit another, with a bit more prior planing and possibly some tests in a branch before attacking master like this.

**Comment by JanSchulz** [comment]
I've updated the branch at https://github.com/JanSchulz/drat/tree/windows_binary_packages with one rebased on top of your current head. It seems that github does not closed PRs with new code.

I still would love to have windows binary support added, so please feel free to tell me what I have to improve/change to get that merged...

**Comment by eddelbuettel** [comment]
And I would love to have it too.  (As for the PR you may need a new one. Let's not rush).

A loose idea would be the following:
-- write a helper function or too which return book and answer `isValidSourceFile()` -- essentially by a grep against https://github.com/eddelbuettel/drat/blob/master/R/pruneRepo.R#L8 or variant thereof
-- add a similar helper for binary packages (ie just `foo_zip$` ?)
-- branch the code accordingly but very carefully

`insertRepo()` is already complicated, and got very it is now with too much poking around and error.  "All we need" is to analyse if we deal with source or binary and then switch some of the copy and update operations accordingly.   Well that is the idea.

I may not have time to work much on drat, so having you branch is good.  Having a working (tested) implementation is good too.  I presume you are testing against a 3.1/3.2 repo?

**Comment by JanSchulz** [comment]
I've readded the PR in #16 and will answer the above there, if that's ok?

**Pull request closed without merging**
