### PR TITLE
Support windows and macosx binary packages

### PR DESCRIPTION
**Pull request by JanSchulz**
This commit adds support for windows and macosx binary packages.
Package type is automatically inferred from the filename.

It also creates the package structure
(`./{src|bin/windows|bin/macosx}/contrib/{rversion/|}`) if these
dirs do not exist.

Closes: #4

### CODE REVIEW

**Comment by JanSchulz** [comment]
from #13

> A loose idea would be the following:
> -- write a helper function or two which return book and answer isValidSourceFile() -- essentially by a grep against https://github.com/eddelbuettel/drat/blob/master/R/pruneRepo.R#L8 or variant thereof
> -- add a similar helper isValidBinaryPackage() for binary packages (ie just foo_zip$ ?)
>-- branch the code accordingly but very carefully

The current code is doing it slightly different: it asked what type the package is and constructs the path where to copy the package to accordingly. I could refactor both big switches into two functions which would do `getPackageTypeFromPackage(inputFilename)` and `getFiledirForPackageType(packageType)`

**Comment by JanSchulz** [comment]
I've updated the PR by moving the the main logic into (unexported) functions. I added the possibility to supply R version information to this functions, but didn't expose this in the main 'installPackages()` call. 

The binary support is tested against the R repo for the [jupyter R kernel packages](https://github.com/IRkernel/irkernel.github.io), both for 3.1 and 3.2

**Comment by eddelbuettel** [comment]
Thumbs up for an actual Windows repository.  I still have a Windows box at work (maybe not for long) that I should be able to test on.   I still don't understand by you don't follow the standard naming scheme of using drat and gh-pages.  People _already_ find drat to be confusing, if we add another naming scheme more heads will explode.  I do understand your point that it is "yet another" http-serviceable scheme from GH, but it is a) different leading to yet more explanation and) longer to type.

**Comment by eddelbuettel** [comment]
That said, I do like the new schme with the helper functions. That is much better.

**Comment by JanSchulz** [comment]
@eddelbuettel you mean why not add to a drat subdir? Mainly because I had to do it manually (script [here](https://github.com/IRkernel/IRkernel/issues/90)) and forgot the subdir. And then never used drat to get packages from there, only `install.packages(c("rzmq","repr","IRkernel","IRdisplay"), repos="http://irkernel.github.io/")`.

**Comment by eddelbuettel** [comment]
So supposed you add `drat/` and moved the files / repo, then the usage would be

```
drat::addRepo("irkernel")                                      # short, sweet, simple
install.packages(c("IRkernel","IRdisplay"))           # assuming the other two are Depends anyway
```

which I find much simpler.   Anyway -- your problem :)

I'll play with Windows binaries tomorrow.   I may have a use case.

**Pull request merged**
